export { calculateTotalScore } from "./calculateTotalScore";
export { client } from "./client";
export { filterByTag } from "./filterByTag";
export { findTitles } from "./findTitles";
export { handlePress } from "./handlePress";
export { lastWordOfString } from "./lastWordOfString";
export { orderByTitle } from "./orderByTitle";
export { presentError } from "./presentError";
export { validEmail } from "./validEmail";
